name: Python Test Workflow

on:
 push:
  branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout mode
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v6
        with: 
           python-version: '3.10' 

      - name: Install dependencies
        run:
           pip install -r GitHub_Actions/requirements.txt
      - name: Run tests
        run: pytest GitHub_Actions/test.py  
      
      - name: ruff linting txekeoa        
        run: ruff check .
        
      - name: Login to GitHub Container Registry 
        uses: docker/login-action@v1
        with:
          registry: ghcr.io          
          username: ${{ github.actor }}          
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker image        
        uses: docker/build-push-action@v2        
        with: 
         context: .          
         file: ./Dockerfile           
         push: true          
         tags: ghcr.io/anderazpiazu/agile-metodologia:latest

      - name: Test the built image        
        run: |          
          docker run --rm ghcr.io/${{ github.repository_owner }}/actions-adibidea:latest 
